package com.example.home_work_lection_4_laba

val ACTION_CUSTOM_BROADCAST = BuildConfig.APPLICATION_ID + ".ACTION_CUSTOM_BROADCAST"
val ACTION_CUSTOM_BROADCAST_RANDOM = "ACTION_CUSTOM_BROADCAST_RANDOM"